backendtrying/mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^recipe/', include('polls.urls')),
]

backendtrying/mysite/polls/urls.py
from django.conf.urls import url, include

from . import views


app_name = "polls"
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="polls_index"),
    url(r'^credits/$', views.CreditsView.as_view(), name="credits"),
    url(r'^input_product/$', views.InputProductView.as_view(), name="input_product"),
    url(r'^your_recipe/$', views.YourRecipeView.as_view(), name="your_recipe"),
    url(r'^recipe_detail/(?P<pk>[0-9]+)/$', views.RecipeDetailView.as_view(), name="recipe_detail"),
]

backendtrying/mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError


class Recipe(models.Model):  # модели в базе данных
    title = models.CharField(default="", max_length=50)  # столбцы в таблице в базе
    recipe_text = models.TextField(max_length=1500)
    pub_date = models.DateTimeField('date published')

    recipe_lines = models.ManyToManyField(
        'Food',
        through='RecipeLine',
        through_fields=('recipe', 'ingridient'),
    )

    def __str__(self):
        return self.recipe_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Food(models.Model):
    food_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.food_text


class RecipeLine(models.Model):
    recipe = models.ForeignKey(Recipe)
    ingridient = models.ForeignKey(Food)
    quantity = models.FloatField(default=0)

    def clean(self):
        if self.quantity <= 0:
            raise ValidationError("Minimum no. of ingridients should be less or equal than maximum")
        return super(quantity, self).clean()

backendtrying/mysite/polls/forms.py
from django import forms
from django_select2.forms import ModelSelect2TagWidget
from . import models


class FoodSelect2TagWidget(ModelSelect2TagWidget):
    search_fields = ['food_text__icontains']
    model = models.Food
    label = ''


class FoodModelSelect2TagWidgetForm(forms.ModelForm):
    class Meta:
        model = models.Food
        fields = ['food_text']
        widgets = {
            'food_text': FoodSelect2TagWidget,
        }
        labels = {
            'food_text': '',
        }

backendtrying/mysite/polls/views.py
from django.views import generic
from django.shortcuts import render
from . import models
from .forms import FoodModelSelect2TagWidgetForm


class IndexView(generic.TemplateView):
    template_name = "polls/index.html"


class CreditsView(generic.TemplateView):
    template_name = "polls/credits.html"


class InputProductView(generic.FormView):
    template_name = "polls/input_product.html"
    form_class = FoodModelSelect2TagWidgetForm


class YourRecipeView(generic.TemplateView):
    template_name = "polls/your_recipe.html"

    def get(self, request, *args):
        food_list = request.GET.getlist('food_text')
        food_ids = []
        for item in food_list:
            try:
                food_ids.append(int(item))
            except ValueError:
                pass
        res = models.Recipe.objects.filter(recipe_lines__in=food_ids).distinct()
        # Old algorithm for strict search
        # vals = []
        # food_ids = set(food_ids)
        # for item in res.all():
        #     food_set = set()
        #     for i in item.recipe_lines.values('id'):
        #         food_set.add(i['id'])
        #     if food_ids.issuperset(food_set):
        #         vals.append(item)
        return render(request, self.template_name, {'food_ids': res.all()})


class RecipeDetailView(generic.DetailView):
    model = models.Recipe
    template_name = "polls/recipe_detail.html"

    def get_context_data(self, **kwargs):
        context = super(RecipeDetailView, self).get_context_data(**kwargs)
        recipe_obj = context.get('object')
        recipe_lines = models.RecipeLine.objects.filter(recipe=recipe_obj).all()
        context['recipe_lines'] = recipe_lines
        return context

backendtrying/mysite/polls/templates/polls/base.html
<!DOCTYPE HTML>
<html>
<head>
    <title>{% block title %}(no title){% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/styles.css' %}"/>
    <meta name="description" content="Your food - our recipe">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
</head>
<body>
    <header>
        <nav>
            <a href="{% url 'polls:input_product' %}">Новый поиск</a> |
            <a href="{% url 'polls:credits' %}">Авторы</a>
        </nav>
    </header>
    {% block content %}
    {% endblock %}
    <footer>
        <div class="navbar-fixed-bottom row-fluid">
            <p><em>Taste'O'Clock project<br/>2017</em></p>
        </div>
    </footer>
</body>
</html>

backendtrying/mysite/polls/templates/polls/credits.html
{% extends 'polls/base.html' %}

{% block title %}Credits{% endblock %}

{% block content %}
{% load static %}
<div class="container-fluid">
    <div class="row-fluid">
        <div class="col-xs-12 line">
            <h1>Авторы</h1>
        </div>
    </div>
    <div class="row-fluid">
        <div class="col-xs-12" id="header">
            Герои нашего времени
        </div>
    </div>
    <div class="row-fluid">
        <div class="col-sm-4 col-xs-12">
            <h3>Лера</h3>
            <p>Back-end<br/>шаман</p>
            <!--<a href="mailto:lera.leroi@gmail.com" target="_blank">
                <img src="{% static 'polls/mail-pic.png' %}" width="50px" alt="Mail"/>
            </a>-->
            <a href="https://t.me/" target="_blank">
                <img src="{% static 'polls/telegram-pic.png' %}" width="50px" alt="Telegram"/>
            </a>
        </div>
        <div class="col-sm-4 col-xs-12">
            <h3>Полина</h3>
            <p>Front-end<br/>друид</p>
            <!--<a href="mailto:ponchitaz@yahoo.com" target="_blank">
                <img src="{% static 'polls/mail-pic.png' %}" width="50px" alt="Mail"/>
            </a>-->
            <a href="https://t.me/ponchitaz" target="_blank">
                <img src="{% static 'polls/telegram-pic.png' %}" width="50px" alt="Telegram"/>
            </a>
        </div>
        <div class="col-sm-4 col-xs-12">
            <h3>Сева</h3>
            <p>DevOps<br/>чернокнижник</p>
            <!-- <a href="" target="_blank">
                 <img src="{% static 'polls/mail-pic.png' %}" width="50px" alt="Mail"/>
            </a>-->
            <a href="https://t.me/aleister_atreides" target="_blank">
                 <img src="{% static 'polls/telegram-pic.png' %}" width="50px" alt="Telegram"/>
            </a>
        </div>
    </div>
    <div class="row-fluid">
        <div class="col-xs-12" id="github">
            <a href="https://github.com/apeironuranium/Your-food---our-recipe" target="_blank">
                <img src="{% static 'polls/github-desktop-icon.png' %}" width="100px" alt="GitHub"/>
            </a>
        </div>
    </div>
    <div class="row-fluid">
        <a href="{% url 'polls:polls_index' %}">
            <div class="col-xs-12">
                <em><strong>На главную</strong></em>
            </div>
        </a>
    </div>
</div>
{% endblock %}

backendtrying/mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block title %}Taste'O'Clock project{% endblock %}

{% block content %}
{% load static %}
<div class="container-fluid">
    <div class="row-fluid">
        <div class="col-xs-12">
            <h1>Taste'O'Clock</h1>
        </div>
    </div>
    <div class="row-fluid"  id="content">
        <div class="col-xs-12" id="header">
            Добро пожаловать в Taste'O'Clock!
        </div>
        <div class="col-xs-12">
            Цель сайта:<br/>рассказать Вам о рецептах,<br/>которые Вы можете приготовить прямо сейчас<br/>из того, что есть под рукой
        </div>
    </div>
    <div class="row-fluid">
        <div class="col-xs-12">
            <a href="{% url 'polls:input_product' %}"><div class="line"><em><strong>Начать</strong></em></div></a>
        </div>
    </div>
</div>
{% endblock %}

backendtrying/mysite/polls/templates/polls/input_product.html
{% extends 'polls/base.html' %}

{% block title %}Taste'O'Clock input{% endblock %}

{% block content %}
{% load static %}
<div class="container-fluid">
    {{ form.media.css }}
    <div clas="row-fluid">
        <div class="col-xs-12">
            <h1>Что у Вас есть?</h1>
        </div>
    </div>
    <div class="row-fluid" id="content">
        <div class="col-xs-12" id="header">
            Выберите из списка продукты, <br/>которые Вы хотите приготовить:
        </div>
        <div class="col-xs-12">
        <style type="text/css">
          select {
            width: 80%;
          }
        </style>
            <form method="get" action="{% url 'polls:your_recipe' %}">
              {% csrf_token %}
              {{ form }}</br>
              <input type="submit" value="Submit Form"/>
            </form>
        </div>
    </div>
</div>
<script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
<script type="text/javascript">
  window.onerror = function (msg) {
    $("body").attr("JSError", msg);
  }
</script>
{{ form.media.js }}
{% endblock %}

backendtrying/mysite/polls/templates/polls/recipe_detail.html
{% extends 'polls/base.html' %}

{% block title %}{{ object.title }} — Taste'O'Clock{% endblock %}

{% block content %}
{% load static %}
<div class="container-fluid">
    <div class="row-fluid">
        <div class="col-xs-12">
            <h1>Ваше будущее блюдо</h1>
        </div>
    </div>
    <div class="row-fluid" id="content">
        <div class="col-xs-12" id="header">
                {{ object.title }}
        </div>
            <div class="col-xs-12 col-sm-6 col-sm-offset-2 col-md-6 col-md-offset-4 recipe-description">
                <h4>Ингридиенты</h4>
                <ul>
                    {% for line in recipe_lines %}
                    <li>{{ line.ingridient }} {{ line.quantity }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-xs-12 col-sm-6 col-sm-offset-2 col-md-6 col-md-offset-4 recipe-description">
                <h4>Способ приготовления</h4>
                    {{ object.recipe_text }}
            </div>
    </div>
    <div class="row-fluid">
        <div class="col-xs-12">
            <a href="{% url 'polls:input_product' %}"><div class="line"><em><strong>Новый поиск</strong></em></div></a>
        </div>
    </div>
</div>

    <!--<div class="line"><em><strong>...</strong></em></div>-->

{% endblock %}

backendtrying/mysite/polls/templates/polls/your_recipe.html
{% extends 'polls/base.html' %}

{% block title %}Taste'O'Clock project{% endblock %}

{% block content %}
{% load static %}
<div class="container-fluid">
    <div class="row-fluid">
        <div class="col-xs-12">
            <h1>Доступные рецепты</h1>
        </div>
    </div>
    <div class="row-fluid" id="content">
        <div class="col-xs-12 col-sm-6 col-sm-offset-2 col-md-6 col-md-offset-4 recipe-description">
        {% if food_ids %}
            <ul class="result-list">
            {% for res in food_ids %}
                <li>
                    <a href="{% url 'polls:recipe_detail' res.id %}">{{ res.title }}</a>
                </li>
            {% endfor %}
            </ul>
            {% else %}
                <p>Ничего не найдено, попробуйте снова.</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}